#!/usr/bin/env bash
set -euo pipefail

# sync-rules.sh — Sync Sentinel rules to a target repository
#
# Usage: ./scripts/sync-rules.sh /path/to/target-repo
#
# This script:
#   1. Copies .md files to <target>/.agents/rules/
#   2. Converts to .mdc files in <target>/.cursor/rules/ (strips Hugo-specific frontmatter)
#   3. Auto-generates <target>/AGENTS.md with a routing table

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RULES_DIR="$PROJECT_ROOT/content/rules"

if [ $# -lt 1 ]; then
    echo "Usage: $0 /path/to/target-repo"
    exit 1
fi

TARGET="$1"

if [ ! -d "$TARGET" ]; then
    echo "Error: Target directory '$TARGET' does not exist."
    exit 1
fi

# Create output directories
mkdir -p "$TARGET/.agents/rules"
mkdir -p "$TARGET/.cursor/rules"

echo "Syncing rules from $RULES_DIR to $TARGET ..."

# ── 1. Copy .md files to .agents/rules/ ─────────────────────────
for file in "$RULES_DIR"/*.md; do
    [ -f "$file" ] || continue
    basename="$(basename "$file")"
    # Skip section index
    [ "$basename" = "_index.md" ] && continue
    cp "$file" "$TARGET/.agents/rules/$basename"
    echo "  .agents/rules/$basename"
done

# ── 2. Convert to .mdc for .cursor/rules/ ───────────────────────
# Strips Hugo-specific keys (title, tags, weight) from frontmatter
for file in "$RULES_DIR"/*.md; do
    [ -f "$file" ] || continue
    basename="$(basename "$file")"
    [ "$basename" = "_index.md" ] && continue

    mdc_name="${basename%.md}.mdc"

    awk '
    BEGIN { in_front=0; front_done=0 }
    /^---$/ && !in_front && !front_done { in_front=1; print; next }
    /^---$/ && in_front { in_front=0; front_done=1; print; next }
    in_front && /^(title|tags|weight):/ { next }
    { print }
    ' "$file" > "$TARGET/.cursor/rules/$mdc_name"

    echo "  .cursor/rules/$mdc_name"
done

# ── 3. Generate AGENTS.md ───────────────────────────────────────
AGENTS_FILE="$TARGET/AGENTS.md"

cat > "$AGENTS_FILE" << 'HEADER'
# AGENTS.md

> Auto-generated by [Project Sentinel](https://github.com/your-org/sentinel).
> Do not edit manually — changes will be overwritten on next sync.

## Rule Routing Table

| Rule | Globs | Always Apply |
|------|-------|-------------|
HEADER

# Build routing table rows
for file in "$RULES_DIR"/*.md; do
    [ -f "$file" ] || continue
    basename="$(basename "$file")"
    [ "$basename" = "_index.md" ] && continue

    rule_name="${basename%.md}"

    # Extract frontmatter values using awk
    globs=$(awk '/^---$/{c++; next} c==1 && /^globs:/{gsub(/^globs: */, ""); print; exit}' "$file")
    always=$(awk '/^---$/{c++; next} c==1 && /^alwaysApply:/{gsub(/^alwaysApply: */, ""); print; exit}' "$file")
    description=$(awk '/^---$/{c++; next} c==1 && /^description:/{gsub(/^description: *"?/, ""); gsub(/"$/, ""); print; exit}' "$file")

    [ -z "$globs" ] && globs="—"
    [ -z "$always" ] && always="false"

    printf '| %s | `%s` | %s |\n' "$rule_name" "$globs" "$always" >> "$AGENTS_FILE"
done

cat >> "$AGENTS_FILE" << 'MIDDLE'

## File Locations

Rules are available in multiple formats for different AI agents:

- **AGENTS.md** (this file) — Routing table and rule references (OpenAI Codex, GitHub Copilot, Google Jules)
- **`.agents/rules/*.md`** — Full rule files in Markdown (AGENTS.md-compatible agents)
- **`.cursor/rules/*.mdc`** — Cursor-compatible rule files (Hugo metadata stripped)

## Rules

MIDDLE

# Append each rule as a section
for file in "$RULES_DIR"/*.md; do
    [ -f "$file" ] || continue
    basename="$(basename "$file")"
    [ "$basename" = "_index.md" ] && continue

    rule_name="${basename%.md}"
    description=$(awk '/^---$/{c++; next} c==1 && /^description:/{gsub(/^description: *"?/, ""); gsub(/"$/, ""); print; exit}' "$file")
    globs=$(awk '/^---$/{c++; next} c==1 && /^globs:/{gsub(/^globs: */, ""); print; exit}' "$file")

    printf -- '### %s\n\n' "$rule_name" >> "$AGENTS_FILE"
    printf -- '- **Description:** %s\n' "${description:-No description}" >> "$AGENTS_FILE"
    printf -- '- **Globs:** `%s`\n' "${globs:-N/A}" >> "$AGENTS_FILE"
    printf -- '- **File:** `.agents/rules/%s`\n\n' "$basename" >> "$AGENTS_FILE"
done

echo ""
echo "Generated $AGENTS_FILE"
echo ""
echo "Sync complete."
